name: Auto Assign - other


on:
  pull_request_target:
    types: ["opened", "ready_for_review"]


jobs:
  add-reviews:
    if: github.actor != 'dependabot'
    runs-on: ubuntu-22.04

    steps:
      # https://github.com/kentaro-m/auto-assign-action
      - name: Auto Assign
        uses: kentaro-m/auto-assign-action@v2.0.0
        with:
          configuration-path: .github/auto-assign-other_config.yml
